### ISSUE TITLE
Want To Know The Data Format

### ISSUE THREAD

**Issue by Scagin** [HarshKohli/UnifiedAttentionModel#1]
I'm happy to see the code you wrote. It's really a magical attention model. Can you please provide a data set, I would like to know what the data format is, to facilitate my improvement of the project. Here is my contact 406493851@qq.com. By the way, is this the realization of a certain document?
Thank you!!

**Comment by HarshKohli** [comment]
Hi,

I've included a readme with instructions on data/preprocessing and training. However, please bear in mind this project is in its very early stages of development.
